CREATE SCHEMA IF NOT EXISTS Startup;
USE Startup;

# RICORDIAMOCI LA NORMALIZZAZIONE DELL'INDIRIZZO SU TUTTI NELLO SCHEMA RELAZIONALE
#SI ASSUME CHE LA MAIL SIA UNICA
CREATE TABLE MEDICO(
    C_F_MEDICO   	CHAR(16)            NOT NULL,
	NOME_MED     	VARCHAR(20)     	NOT NULL,
    COGNOME_MED     VARCHAR(20)     	NOT NULL,
    EMAIL			VARCHAR(30)			NOT NULL,
    DOB             DATE
    TELEFONO    	VARCHAR(15),
    VIA         	VARCHAR(30),
    CIVICO      	VARCHAR(4),
    CAP         	VARCHAR(5),
    CITTA       	VARCHAR(10),
    PRIMARY KEY(C_F_MEDICO),
    UNIQUE(EMAIL)
);


CREATE TABLE PAZIENTE(
    C_F_PAZIENTE    CHAR(16)        NOT NULL,
	NOME_PAZ     	VARCHAR(20)     NOT NULL,
    COGNOME_PAZ     VARCHAR(20)     NOT NULL,
    EMAIL			VARCHAR(30)		NOT NULL,
    DOB             DATE
    C_F_MEDICO		CHAR(16),
    TELEFONO    	VARCHAR(15),
    VIA         	VARCHAR(30),
    CIVICO      	VARCHAR(4),
    CAP         	VARCHAR(5),
    CITTA       	VARCHAR(10),
    PRIMARY KEY(C_F_PAZIENTE),
    UNIQUE(EMAIL),
    FOREIGN KEY(C_F_MEDICO) REFERENCES MEDICO(C_F_MEDICO)
        ON DELETE CASCADE ON UPDATE CASCADE
);
#QUANDO IL MEDICO VIENE ELIMINATO L'UTENTE(PAZIENTE) TORNA ALLO STATO "SENZA MEDICO"

CREATE TABLE VISITA(
	ID				INT				NOT NULL, #INSERITO AUTOMATICAMENTE DALL'APPLICATIVO WEB(PROGRESSIVO)
    C_F_MEDICO		CHAR(16)		NOT NULL,
    C_F_PAZIENTE    CHAR(16)        NOT NULL,
    DATA_VISITA		DATETIME		NOT NULL, 
    #TOCCA FARLA UNICA PERCHÈ ESISTE O SOLO PER LA DATA O PER DATA E ORARIO INSIEME
    PRIMARY KEY(ID),
    FOREIGN KEY(C_F_PAZIENTE) REFERENCES PAZIENTE(C_F_PAZIENTE)
        ON DELETE NO ACTION ON UPDATE CASCADE,
    FOREIGN KEY(C_F_MEDICO) REFERENCES MEDICO(C_F_MEDICO)
        ON DELETE NO ACTION ON UPDATE CASCADE
#ANCHE SE PAZIENTE E MEDICO NON CI FOSSERO PIÙ L'INFORMAZIONE DELLA VISITA È
#RAGIONEVOLE CHE VENGA MANTENUTA L'INTERA INFORMAZIONE
);
CREATE TABLE PRODOTTO(
    RIFERIMENTO     VARCHAR(100)    NOT NULL
	AIC         	CHAR(8)	        NOT NULL,
    NOME			VARCHAR(30) 	NOT NULL,
    PREZZO			FLOAT	    	NOT NULL,
    PRIMARY KEY(AID),
    UNIQUE(NOME),
);
#NRE
#https://sistemats1.sanita.finanze.it/portale/documents/20182/33285/gestione%2BNRE_24_05_2012.pdf/42dadb9f-9c5a-aec0-c5de-a379c41d086e
CREATE TABLE RICETTA(
	NRE				CHAR(15)		NOT NULL, 
    DATA_RICETTA	DATE			NOT NULL, 
    AID         	CHAR(8)     	NOT NULL, #DOBBIAMO DECIDERE CHE CODICI DARE AI PRODOTTI
    C_F_MEDICO		CHAR(16)		NOT NULL,
    C_F_PAZIENTE    CHAR(16)        NOT NULL,
    UTILIZZATA      BIT             NOT NULL,   #0 = FALSE 1 = TRUE
    PRIMARY KEY(NRE),
    FOREIGN KEY(AID) REFERENCES PRODOTTO(AID)
        ON DELETE NO ACTION ON UPDATE CASCADE,
    FOREIGN KEY(C_F_PAZIENTE) REFERENCES PAZIENTE(C_F_PAZIENTE)
        ON DELETE NO ACTION ON UPDATE CASCADE,
    FOREIGN KEY(C_F_MEDICO) REFERENCES MEDICO(C_F_MEDICO)
        ON DELETE NO ACTION ON UPDATE CASCADE
#ANCHE SE PAZIENTE, MEDICO O PRODOTTO NON CI FOSSERO PIÙ NEL DB, NELLA RICETTA È
#RAGIONEVOLE CHE VENGA MANTENUTA L'INTERA INFORMAZIONE
);
CREATE TABLE FARMACIA(
    P_IVA           CHAR(11)        NOT NULL,
    ORARI_APERTURA  DATETIME        NOT NULL,
    NOME            VARCHAR(100)    NOT NULL,
    VIA         	VARCHAR(30)     NOT NULL,
    CIVICO      	VARCHAR(4)      NOT NULL,
    CAP         	VARCHAR(5)      NOT NULL,
    CITTA       	VARCHAR(10)     NOT NULL,    
    PRIMARY KEY(P_IVA)
);

CREATE TABLE POSSIEDE(
    P_IVA       CHAR(11)   NOT NULL,
    AID         CHAR(8)    NOT NULL,
    QUANTITA    INT        NOT NULL,
    FOREIGN KEY(AID) REFERENCES PRODOTTO(AID)#TOLTO PERCHE PROBLEATICO PROBABILMENTE
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(P_IVA) REFERENCES FARMCIA(P_IVA)
        ON DELETE CASCADE ON UPDATE CASCADE,
);

CREATE TABLE ORDINE(
    
);